export const ACTION_TYPE = {
  AUDIT_START: 'AUDIT_START',
  AUDIT_STOP: 'AUDIT_STOP',
  LAST_PING_SET: 'LAST_PING_SET',
  LOCATION_SET: 'LOCATION_SET',
};

export const DATABASE_NAME = 'service-auditor';
